#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# ── Stage Times: provision the three deployment secrets (ticket 03) ──────
#
#   ANTHROPIC_API_KEY  vision calls bill the API, never the owner's subscription
#   GITHUB_TOKEN       fine-grained token: contents + pull requests write on the repo
#   OWNER_SECRET       what the owner's bookmarked link is checked against
#
# Names are fixed in src/secrets.ts. Values go to Vercel (production + preview)
# through the Vercel CLI; nothing is ever committed, logged, or written to the
# vault. Re-run any time to rotate: each stage offers to replace what exists.

cd "$(dirname "$0")/.." || exit 1
REPO_SLUG="jake-lunde/stage-times"
SITE="https://stagetimes.app"
VERCEL="npx --yes vercel@latest"
VERCEL_ENVS=(production preview)

# vercel_has NAME ENV: is NAME already set for ENV on the linked project?
vercel_has() {
  $VERCEL env ls "$2" 2>/dev/null | awk '{print $1}' | grep -qx "$1"
}

# set_vercel_env NAME VALUE: upsert NAME for production and preview. Tries
# --sensitive first (value unreadable after creation), falls back without it.
set_vercel_env() {
  local name="$1" value="$2" env
  for env in "${VERCEL_ENVS[@]}"; do
    if vercel_has "$name" "$env"; then
      $VERCEL env rm "$name" "$env" --yes >/dev/null 2>&1 || true
    fi
    if printf '%s' "$value" | $VERCEL env add "$name" "$env" --sensitive >/dev/null 2>&1 \
      || printf '%s' "$value" | $VERCEL env add "$name" "$env" >/dev/null 2>&1; then
      printf '  %s✓ set%s Vercel %s (%s)\n' "$GREEN" "$RESET" "$name" "$env"
    else
      SKIPPED+=("Vercel env $name ($env) — set it in the dashboard: Settings → Environment Variables")
      warn "could not set $name for $env; add it in the Vercel dashboard"
    fi
  done
}

# health [OWNER_SECRET]: GET (or POST with the owner secret) $SITE/api/health.
health() {
  if [[ -n "${1:-}" ]]; then
    curl -fsS -X POST -H 'Content-Type: application/json' \
      --data "$(node -e 'console.log(JSON.stringify({owner: process.argv[1]}))' "$1")" \
      "$SITE/api/health" 2>/dev/null
  else
    curl -fsS "$SITE/api/health" 2>/dev/null
  fi
}

banner "Stage Times: provision secrets"

# ── 1. Vercel CLI ─────────────────────────────────────────────────────────
stage "Vercel CLI: sign in, confirm the project"
say "The next stages write environment variables with the Vercel CLI (run via npx,"
say "nothing installed globally). It needs you signed in to the LUNDE OS team."
if [[ -f .vercel/project.json ]] && grep -q '"projectName":"stage-times"' .vercel/project.json; then
  note "linked project: stage-times (from .vercel/project.json)"
else
  warn "this checkout is not linked to the stage-times project"
  step "Run: npx vercel link   — pick the LUNDE OS team and the stage-times project, then re-run."
  exit 1
fi
if $VERCEL whoami >/dev/null 2>&1; then
  note "signed in as: $($VERCEL whoami 2>/dev/null | tail -n1)"
else
  step "A browser window will open to sign you in to Vercel. Approve it, then come back."
  $VERCEL login || { warn "Vercel login failed; sign in and re-run."; exit 1; }
fi
say "Already set on Vercel (production):"
for n in ANTHROPIC_API_KEY GITHUB_TOKEN OWNER_SECRET; do
  if vercel_has "$n" production; then note "  ✓ $n"; else note "  · $n (not yet)"; fi
done
pause

# ── 2. Anthropic API key ──────────────────────────────────────────────────
stage "Anthropic: API key for vision calls"
say "Transcription must bill the API, not your Claude subscription. Make a key just"
say "for this site so it can be revoked on its own."
if vercel_has ANTHROPIC_API_KEY production && ! confirm "ANTHROPIC_API_KEY already exists on Vercel. Replace it (rotate)?"; then
  note "keeping the existing key"
  # The hourly watcher runs on GitHub Actions and needs the same key there.
  if local_key=$(grep -s '^ANTHROPIC_API_KEY=' "$ENV_FILE" | head -n1 | cut -d= -f2-) && [[ -n "$local_key" ]]; then
    set_secret ANTHROPIC_API_KEY "$local_key"
  else
    SKIPPED+=("GitHub secret ANTHROPIC_API_KEY (no local copy in $ENV_FILE; run: gh secret set ANTHROPIC_API_KEY)")
    warn "no local copy of the key in $ENV_FILE to set the GitHub secret from"
  fi
else
  open_url "https://console.anthropic.com/settings/keys"
  step "Click 'Create Key'. Name it 'stagetimes-vercel'. Pick the workspace you bill from."
  step "Copy the key — it is shown once."
  ask_secret ANTHROPIC_API_KEY "Paste the API key:"
  if [[ -z "$ANTHROPIC_API_KEY" ]]; then warn "empty; skipping"; else
    write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"   # local: npm run ingest reads it (set -a; . ./.env; set +a)
    set_vercel_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
    set_secret ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"  # GitHub Actions: the hourly watcher (.github/workflows/watch.yml)
  fi
fi
pause

# ── 3. GitHub token ───────────────────────────────────────────────────────
stage "GitHub: fine-grained token for the publisher"
say "The upload flow commits edition YAML to main and opens listing pull requests."
say "A fine-grained token scoped to this one repo is all it gets."
if vercel_has GITHUB_TOKEN production && ! confirm "GITHUB_TOKEN already exists on Vercel. Replace it (rotate)?"; then
  note "keeping the existing token"
else
  open_url "https://github.com/settings/personal-access-tokens/new"
  step "Token name: stagetimes-publisher"
  step "Expiration: the longest offered. Note the date — an expired token fails silently later."
  step "Resource owner: jake-lunde"
  step "Repository access: 'Only select repositories' → $REPO_SLUG"
  step "Repository permissions: Contents → Read and write; Pull requests → Read and write."
  step "(Metadata → Read is added automatically.) Nothing else."
  step "Click 'Generate token' and copy it — it is shown once."
  ask_secret GITHUB_TOKEN "Paste the token:"
  if [[ -z "$GITHUB_TOKEN" ]]; then warn "empty; skipping"; else
    set_vercel_env GITHUB_TOKEN "$GITHUB_TOKEN"        # deployment only; nothing local needs it
  fi
fi
pause

# ── 4. Owner secret ───────────────────────────────────────────────────────
stage "Owner secret: the bookmarked link"
say "The owner publishes through the same upload screens as a fan, recognized by a"
say "secret carried in a bookmarked link. The secret is generated here, never typed."
OWNER_SECRET=""
if vercel_has OWNER_SECRET production && ! confirm "OWNER_SECRET already exists on Vercel. Rotate it? (the old bookmark stops working)"; then
  note "keeping the existing secret; the bookmark you stored stays valid"
else
  if command -v openssl >/dev/null 2>&1; then
    OWNER_SECRET=$(openssl rand -hex 32)
  else
    OWNER_SECRET=$(node -e 'console.log(require("crypto").randomBytes(32).toString("hex"))')
  fi
  set_vercel_env OWNER_SECRET "$OWNER_SECRET"
  LINK="$SITE/upload/#owner=$OWNER_SECRET"
  printf '\n'
  say "Your owner link (the secret rides in the URL fragment, which never reaches a"
  say "server log; the page sends it with each post). Runbook: docs/owner-runbook.md"
  printf '\n    %s%s%s\n\n' "$BOLD" "$LINK" "$RESET"
  if command -v pbcopy >/dev/null 2>&1; then printf '%s' "$LINK" | pbcopy; note "(copied to your clipboard)"; fi
  warn "Store it in 1Password now. It is not saved anywhere else and will not be shown again."
  warn "To rotate later: re-run this script and say yes at this stage."
fi
pause "Stored? Press Enter to continue."

# ── 5. Deploy and verify ──────────────────────────────────────────────────
stage "Deploy and verify from a deployment"
say "Environment variables reach only deployments made after they were set, so a new"
say "deploy is needed. Then $SITE/api/health reports which secrets a"
say "deployment can read, and — given the owner secret — proves each key works."
HEAD_SHA=$(git rev-parse HEAD)
PUSHED=0
AHEAD=$(git rev-list --count origin/main..main 2>/dev/null || echo 0)
if [[ "$AHEAD" != "0" ]]; then
  say "main is $AHEAD commit(s) ahead of origin/main."
  if confirm "Push main now? (this deploys to production)"; then
    git push origin main && PUSHED=1
  else
    warn "not pushed; a deploy is still needed for the new variables to take effect"
  fi
fi
# Only offer a redeploy when nothing was just pushed. A redeploy rebuilds
# whatever $SITE points at *right now*; issued alongside a fresh push it
# rebuilds the previous commit and then steals the alias back from the new one
# (this happened on the first run). The poll below checks the commit, so a
# stale alias is caught either way.
if (( ! PUSHED )) && confirm "Redeploy the current production deployment so it picks up the new variables?"; then
  $VERCEL redeploy "$SITE" >/dev/null 2>&1 \
    || { warn "vercel redeploy did not work here; in the dashboard: Deployments → ⋯ → Redeploy"; open_url "https://vercel.com/lunde-os/stage-times"; pause "Redeploy started?"; }
fi
say "Waiting for a deployment of ${HEAD_SHA:0:7} that can see all three secrets (up to 5 minutes)…"
DEADLINE=$(( $(date +%s) + 300 )); READY=0; STALE=""
while (( $(date +%s) < DEADLINE )); do
  if H=$(health); then
    if node -e 'const h=JSON.parse(require("fs").readFileSync(0,"utf8")); process.exit((h.deployment===process.argv[1])&&Object.values(h.secrets).every(Boolean)?0:1)' "$HEAD_SHA" <<<"$H" 2>/dev/null; then
      READY=1; break
    fi
    STALE=$(node -e 'const h=JSON.parse(require("fs").readFileSync(0,"utf8")); console.log(String(h.deployment||"").slice(0,7))' <<<"$H" 2>/dev/null || true)
  fi
  sleep 10; printf '.'
done
printf '\n'
if (( READY )); then
  printf '%s\n' "$H" | node -e 'const h=JSON.parse(require("fs").readFileSync(0,"utf8")); console.log(`  deployment ${h.deployment} (${h.env})`); for (const [k,v] of Object.entries(h.secrets)) console.log(`  ${v?"✓":"✗"} ${k}`)'
else
  warn "no deployment of ${HEAD_SHA:0:7} reported all three secrets within 5 minutes."
  if [[ -n "$STALE" && "$STALE" != "${HEAD_SHA:0:7}" ]]; then
    warn "production is serving $STALE, not ${HEAD_SHA:0:7}. Promote the right deployment:"
    note "  npx vercel ls --prod        # find the deployment built from ${HEAD_SHA:0:7}"
    note "  npx vercel promote <url>    # alias it to $SITE"
  else
    note "  curl $SITE/api/health"
  fi
fi
if [[ -z "$OWNER_SECRET" ]]; then
  say "To prove the keys work, the health check needs the owner secret (from your bookmark)."
  ask_secret OWNER_SECRET "Paste the owner secret (or Enter to skip):"
fi
if [[ -n "$OWNER_SECRET" ]]; then
  if L=$(health "$OWNER_SECRET"); then
    printf '%s\n' "$L" | node -e '
      const h=JSON.parse(require("fs").readFileSync(0,"utf8"));
      if (!h.owner) { console.log("  ✗ owner secret not recognized by this deployment (not set yet, or an older deployment is still live)"); process.exit(0); }
      console.log("  ✓ owner secret recognized");
      for (const [k,v] of Object.entries(h.live)) console.log(`  ${v.ok?"✓":"✗"} ${k}: ${v.detail}`);'
  else
    warn "health check request failed"
  fi
fi
note "Live checks cannot probe pull-request write without opening a PR; ticket 10 exercises it."
pause

finish
